// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/testing/test.proto

package grpc.testing;

/**
 *  ******* DO NOT EDIT *******
 * Generated by proto compiler from protos in the following dir
 *     https://github.com/grpc/grpc/tree/master/src/proto/grpc/testing
 */
public final class TestFromProto {
  private TestFromProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027grpc/testing/test.proto\022\014grpc.testing\032" +
      "\030grpc/testing/empty.proto\032\033grpc/testing/" +
      "messages.proto2\313\005\n\013TestService\0225\n\tEmptyC" +
      "all\022\023.grpc.testing.Empty\032\023.grpc.testing." +
      "Empty\022F\n\tUnaryCall\022\033.grpc.testing.Simple" +
      "Request\032\034.grpc.testing.SimpleResponse\022O\n" +
      "\022CacheableUnaryCall\022\033.grpc.testing.Simpl" +
      "eRequest\032\034.grpc.testing.SimpleResponse\022l" +
      "\n\023StreamingOutputCall\022(.grpc.testing.Str" +
      "eamingOutputCallRequest\032).grpc.testing.S",
      "treamingOutputCallResponse0\001\022i\n\022Streamin" +
      "gInputCall\022\'.grpc.testing.StreamingInput" +
      "CallRequest\032(.grpc.testing.StreamingInpu" +
      "tCallResponse(\001\022i\n\016FullDuplexCall\022(.grpc" +
      ".testing.StreamingOutputCallRequest\032).gr" +
      "pc.testing.StreamingOutputCallResponse(\001" +
      "0\001\022i\n\016HalfDuplexCall\022(.grpc.testing.Stre" +
      "amingOutputCallRequest\032).grpc.testing.St" +
      "reamingOutputCallResponse(\0010\001\022=\n\021Unimple" +
      "mentedCall\022\023.grpc.testing.Empty\032\023.grpc.t",
      "esting.Empty2U\n\024UnimplementedService\022=\n\021" +
      "UnimplementedCall\022\023.grpc.testing.Empty\032\023" +
      ".grpc.testing.Empty2\211\001\n\020ReconnectService" +
      "\022;\n\005Start\022\035.grpc.testing.ReconnectParams" +
      "\032\023.grpc.testing.Empty\0228\n\004Stop\022\023.grpc.tes" +
      "ting.Empty\032\033.grpc.testing.ReconnectInfo2" +
      "\177\n\030LoadBalancerStatsService\022c\n\016GetClient" +
      "Stats\022&.grpc.testing.LoadBalancerStatsRe" +
      "quest\032\'.grpc.testing.LoadBalancerStatsRe" +
      "sponse\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.testing.EmptyOuterClass.getDescriptor(),
          grpc.testing.Messages.getDescriptor(),
        }, assigner);
    grpc.testing.EmptyOuterClass.getDescriptor();
    grpc.testing.Messages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
