/**
 * @fileoverview gRPC-Web generated client stub for grpc.gateway.testing
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: protos/echo.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protos_echo_pb from '../protos/echo_pb'; // proto import: "protos/echo.proto"


export class EchoServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorEcho = new grpcWeb.MethodDescriptor(
    '/grpc.gateway.testing.EchoService/Echo',
    grpcWeb.MethodType.UNARY,
    protos_echo_pb.EchoRequest,
    protos_echo_pb.EchoResponse,
    (request: protos_echo_pb.EchoRequest) => {
      return request.serializeBinary();
    },
    protos_echo_pb.EchoResponse.deserializeBinary
  );

  echo(
    request: protos_echo_pb.EchoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<protos_echo_pb.EchoResponse>;

  echo(
    request: protos_echo_pb.EchoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protos_echo_pb.EchoResponse) => void): grpcWeb.ClientReadableStream<protos_echo_pb.EchoResponse>;

  echo(
    request: protos_echo_pb.EchoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protos_echo_pb.EchoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpc.gateway.testing.EchoService/Echo',
        request,
        metadata || {},
        this.methodDescriptorEcho,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpc.gateway.testing.EchoService/Echo',
    request,
    metadata || {},
    this.methodDescriptorEcho);
  }

  methodDescriptorEchoAbort = new grpcWeb.MethodDescriptor(
    '/grpc.gateway.testing.EchoService/EchoAbort',
    grpcWeb.MethodType.UNARY,
    protos_echo_pb.EchoRequest,
    protos_echo_pb.EchoResponse,
    (request: protos_echo_pb.EchoRequest) => {
      return request.serializeBinary();
    },
    protos_echo_pb.EchoResponse.deserializeBinary
  );

  echoAbort(
    request: protos_echo_pb.EchoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<protos_echo_pb.EchoResponse>;

  echoAbort(
    request: protos_echo_pb.EchoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protos_echo_pb.EchoResponse) => void): grpcWeb.ClientReadableStream<protos_echo_pb.EchoResponse>;

  echoAbort(
    request: protos_echo_pb.EchoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protos_echo_pb.EchoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpc.gateway.testing.EchoService/EchoAbort',
        request,
        metadata || {},
        this.methodDescriptorEchoAbort,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpc.gateway.testing.EchoService/EchoAbort',
    request,
    metadata || {},
    this.methodDescriptorEchoAbort);
  }

  methodDescriptorNoOp = new grpcWeb.MethodDescriptor(
    '/grpc.gateway.testing.EchoService/NoOp',
    grpcWeb.MethodType.UNARY,
    protos_echo_pb.Empty,
    protos_echo_pb.Empty,
    (request: protos_echo_pb.Empty) => {
      return request.serializeBinary();
    },
    protos_echo_pb.Empty.deserializeBinary
  );

  noOp(
    request: protos_echo_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<protos_echo_pb.Empty>;

  noOp(
    request: protos_echo_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protos_echo_pb.Empty) => void): grpcWeb.ClientReadableStream<protos_echo_pb.Empty>;

  noOp(
    request: protos_echo_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protos_echo_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpc.gateway.testing.EchoService/NoOp',
        request,
        metadata || {},
        this.methodDescriptorNoOp,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpc.gateway.testing.EchoService/NoOp',
    request,
    metadata || {},
    this.methodDescriptorNoOp);
  }

  methodDescriptorServerStreamingEcho = new grpcWeb.MethodDescriptor(
    '/grpc.gateway.testing.EchoService/ServerStreamingEcho',
    grpcWeb.MethodType.SERVER_STREAMING,
    protos_echo_pb.ServerStreamingEchoRequest,
    protos_echo_pb.ServerStreamingEchoResponse,
    (request: protos_echo_pb.ServerStreamingEchoRequest) => {
      return request.serializeBinary();
    },
    protos_echo_pb.ServerStreamingEchoResponse.deserializeBinary
  );

  serverStreamingEcho(
    request: protos_echo_pb.ServerStreamingEchoRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<protos_echo_pb.ServerStreamingEchoResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/grpc.gateway.testing.EchoService/ServerStreamingEcho',
      request,
      metadata || {},
      this.methodDescriptorServerStreamingEcho);
  }

  methodDescriptorServerStreamingEchoAbort = new grpcWeb.MethodDescriptor(
    '/grpc.gateway.testing.EchoService/ServerStreamingEchoAbort',
    grpcWeb.MethodType.SERVER_STREAMING,
    protos_echo_pb.ServerStreamingEchoRequest,
    protos_echo_pb.ServerStreamingEchoResponse,
    (request: protos_echo_pb.ServerStreamingEchoRequest) => {
      return request.serializeBinary();
    },
    protos_echo_pb.ServerStreamingEchoResponse.deserializeBinary
  );

  serverStreamingEchoAbort(
    request: protos_echo_pb.ServerStreamingEchoRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<protos_echo_pb.ServerStreamingEchoResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/grpc.gateway.testing.EchoService/ServerStreamingEchoAbort',
      request,
      metadata || {},
      this.methodDescriptorServerStreamingEchoAbort);
  }

}

