/**
 * @fileoverview gRPC-Web generated client stub for grpc.gateway.testing
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: protos/hello.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protos_hello_pb from '../protos/hello_pb'; // proto import: "protos/hello.proto"


export class HelloServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorsayHello = new grpcWeb.MethodDescriptor(
    '/grpc.gateway.testing.HelloService/sayHello',
    grpcWeb.MethodType.UNARY,
    protos_hello_pb.HelloRequest,
    protos_hello_pb.HelloResponse,
    (request: protos_hello_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    protos_hello_pb.HelloResponse.deserializeBinary
  );

  sayHello(
    request: protos_hello_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null): Promise<protos_hello_pb.HelloResponse>;

  sayHello(
    request: protos_hello_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protos_hello_pb.HelloResponse) => void): grpcWeb.ClientReadableStream<protos_hello_pb.HelloResponse>;

  sayHello(
    request: protos_hello_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protos_hello_pb.HelloResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpc.gateway.testing.HelloService/sayHello',
        request,
        metadata || {},
        this.methodDescriptorsayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpc.gateway.testing.HelloService/sayHello',
    request,
    metadata || {},
    this.methodDescriptorsayHello);
  }

  methodDescriptorsayGoodbye = new grpcWeb.MethodDescriptor(
    '/grpc.gateway.testing.HelloService/sayGoodbye',
    grpcWeb.MethodType.UNARY,
    protos_hello_pb.HelloRequest,
    protos_hello_pb.HelloResponse,
    (request: protos_hello_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    protos_hello_pb.HelloResponse.deserializeBinary
  );

  sayGoodbye(
    request: protos_hello_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null): Promise<protos_hello_pb.HelloResponse>;

  sayGoodbye(
    request: protos_hello_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protos_hello_pb.HelloResponse) => void): grpcWeb.ClientReadableStream<protos_hello_pb.HelloResponse>;

  sayGoodbye(
    request: protos_hello_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protos_hello_pb.HelloResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpc.gateway.testing.HelloService/sayGoodbye',
        request,
        metadata || {},
        this.methodDescriptorsayGoodbye,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpc.gateway.testing.HelloService/sayGoodbye',
    request,
    metadata || {},
    this.methodDescriptorsayGoodbye);
  }

}

