name: Make macOS Plugin

on:
  push:
    paths:
      - .github/workflows/make-plugin-mac-os.yml
  pull_request:
    paths:
      - .github/workflows/make-plugin-mac-os.yml
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number'
        required: true
        default: '2.x.x'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute VERSION_NUMBER
        run: |
          INPUT_VERSION="${{ github.event.inputs.version_number }}"
          if [ -n "$INPUT_VERSION" ]; then
            VERSION="$INPUT_VERSION"
          else
            VERSION="$GITHUB_REF_NAME"
          fi
          # Minimal sanitization: replace slashes with dashes to keep filenames valid
          VERSION="${VERSION//\//-}"
          echo "VERSION_NUMBER=$VERSION" >> "$GITHUB_ENV"
          echo "Computed VERSION_NUMBER=$VERSION"
      - name: Compute ARCH suffix and artifact name
        id: meta
        run: |
          ARCH=$(uname -m)
          case "$ARCH" in
            arm64)
              ARCH_SUFFIX="aarch64"
              ;;
            x86_64)
              ARCH_SUFFIX="x86_64"
              ;;
            *)
              echo "Unsupported architecture: $ARCH" >&2
              exit 1
              ;;
          esac
          ARTIFACT="protoc-gen-grpc-web-${VERSION_NUMBER}-darwin-${ARCH_SUFFIX}"
          echo "ARTIFACT=$ARTIFACT" >> "$GITHUB_ENV"
          echo "artifact=$ARTIFACT" >> "$GITHUB_OUTPUT"
          echo "Will produce artifact: $ARTIFACT"
      - name: Install Bazelisk (Bazel)
        run: |
          brew update
          brew install bazelisk
          bazelisk version
      - name: Build protoc-gen-grpc-web with Bazel
        run: |
          bazelisk build //javascript/net/grpc/web/generator:protoc-gen-grpc-web
      - name: Move artifact
        run: |
          mv bazel-bin/javascript/net/grpc/web/generator/protoc-gen-grpc-web \
            ./${ARTIFACT}
      - name: Generate sha256
        run: |
          openssl dgst -sha256 -r -out ${ARTIFACT}.sha256 \
            ${ARTIFACT}
      - name: Verify sha256
        run: shasum -a 256 -c ${ARTIFACT}.sha256
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.meta.outputs.artifact }}
          path: protoc-gen-grpc-web*
